#define PJ_CONFIG_IPHONE 1
#define PJ_HAS_IPV6 1
#define PJMEDIA_HAS_BCG729 1
#define PJMEDIA_HAS_OPUS_CODEC 1
#define PJMEDIA_HAS_VIDEO 0
#define PJMEDIA_HAS_VID_TOOLBOX_CODEC 0
#define PJSUA_DETECT_MERGED_REQUESTS 0
#define PJ_QOS_IMPLEMENTATION PJ_QOS_BSD
#define PJSIP_TRANSPORT_IDLE_TIME 1
#include <pj/config_site_sample.h>
