#!/bin/sh

set -e

BASE_PATH="${PODS_TARGET_SRCROOT}/lib/include"
PRIVATE_HEADERS_PATH="${BUILT_PRODUCTS_DIR}/${PRIVATE_HEADERS_FOLDER_PATH}"
PUBLIC_HEADERS_PATH="${BUILT_PRODUCTS_DIR}/${PUBLIC_HEADERS_FOLDER_PATH}"

cp -af "${BASE_PATH}/" "${PUBLIC_HEADERS_PATH}/"
